template-repository: "tschm/.config-templates"
template-branch: "main"
include: |
    .github
    tests
    .editorconfig
    .gitignore
    .pre-commit-config.yaml
    CODE_OF_CONDUCT.md
    CONTRIBUTING.md
    Makefile
    ruff.toml
exclude: |
    .github/workflows/docker.yml
