template-repository: "jebel-quant/rhiza"
template-branch: "main"
include: |
    .github
    tests
    .editorconfig
    .gitignore
    .pre-commit-config.yaml
    CODE_OF_CONDUCT.md
    CONTRIBUTING.md
    Makefile
    ruff.toml
    pytest.ini
exclude: |
    .github/workflows/docker.yml
