name: "book"

on:
- push

jobs:
  book:
    runs-on: "ubuntu-latest"
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - uses: cvxgrp/.github/actions/book@main
        with:
          os: ${{ runner.os }}
          python-version: "3.11"
          sphinx-folder: "book/sphinx/"
          source-folder: "cvx"
          kernel: "simulator"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
