name: "ci"

on:
- push

jobs:
  dependencies:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      - name: Export dependencies
        run: |
          poetry show --only main --tree
          mkdir -p artifacts/build
          poetry show --only main --tree > artifacts/build/show.txt
          tree artifacts
          cat artifacts/build/show.txt

      - name: Archive dependencies
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: artifacts/build

  count:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      - name: count
        run: |
            pip install pygount==1.5.1
            mkdir -p artifacts/lines
            pygount --format=summary --out=artifacts/lines/lines.txt cvx
            tree artifacts

      - name: Archive counts
        uses: actions/upload-artifact@v3
        with:
          name: count
          path: artifacts/lines

  sphinx:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      #- name: Install sphinx
      #  run: |
      #    pip install --no-cache-dir \
      #                sphinx==5.0.2 \
      #                sphinx-autoapi==1.8.4 \
      #                sphinx-rtd-theme==1.0.0 \
      #                recommonmark==0.7.1

      - name: Build sphinx
        run: |
          mkdir -p artifacts/sphinx
          sphinx-build -b html docs/ artifacts/sphinx
          ls -all artifacts/sphinx

      - name: Archive sphinx documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx
          path: artifacts/sphinx

  jupyter:
    needs: [sphinx, count, dependencies]

    runs-on: "ubuntu-latest"
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      - name: Install jupyterbook
        run: |
          # poetry run pip install jupyter-book
          poetry run python -m ipykernel install --user --name="simulator"

      # Build the book
      - name: Build the book
        run: |
          poetry run jupyter-book clean book
          poetry run jupyter-book build book

      # Download the counting
      - name: Download count results
        uses: actions/download-artifact@v3
        with:
          name: count
          path: book/_build/html/artifacts/lines

      # Download the sphinx artifact
      - name: Download Sphinx page
        uses: actions/download-artifact@v3
        with:
          name: sphinx
          path: book/_build/html/artifacts/sphinx

      # Download the dependencies artifact
      - name: Download the dependencies file
        uses: actions/download-artifact@v3
        with:
          name: dependencies
          path: book/_build/html/artifacts/build

      # Check uploads
      - name: Inspect upload
        run : |
          tree book/_build/html/artifacts

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html