name: "Count lines of code"

on:
- push

jobs:
  count:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      - name: count
        run: |
            pip install pygount==1.5.1
            mkdir -p artifacts/lines
            pygount --format=summary --out=artifacts/lines/lines.txt cvx

      - name: Archive counts
        uses: actions/upload-artifact@v3
        with:
          name: count
          path: artifacts/lines/lines.txt