name: "Build Sphinx"

on:
- push

jobs:
  docs:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-environment
        with:
          os: ${{ runner.os }}
          python-version: "3.11"

      #----------------------------------------------
      # install sphinx
      #----------------------------------------------
      - name: Install sphinx
        run: | 
          pip install --no-cache-dir \
                      sphinx==5.0.2 \
                      sphinx-autoapi==1.8.4 \
                      sphinx-rtd-theme==1.0.0 \
                      recommonmark==0.7.1

      - name: Build sphinx
        run: |
          mkdir -p artifacts/docs
          sphinx-build -b html docs/ artifacts/docs

      - name: Archive sphinx documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx
          path: artifacts/docs